apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: m3p12s7mx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: m3p12s7mx-go 
  name: m3p12s7mx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: m3p12s7mx-go 
