apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m3p12s7mx-go 
  janus-idp.io/tekton: m3p12s7mx-go
  backstage.io/kubernetes-id: m3p12s7mx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m3p12s7mx-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  